config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :teachers
  resources :students
  root to: 'students#index' # Redirect to student listing after login
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  belongs_to :teacher
  # Validations
  validates :name, presence: true, uniqueness: { scope: :subject, message: 'and subject combination already exists' }
  validates :subject, presence: true
  validates :marks, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :students, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
# frozen_string_literal: true

# student controller
class StudentsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_student, only: %i[edit update destroy]

  def index
    @students = current_teacher.students
  end

  def new
    @student = Student.new
  end

  def create
    @student = current_teacher.students.build(student_params)
    if @student.save
      flash[:notice] = 'Student was successfully created.'
    else
      flash.now[:alert] = 'Error creating student. Please try again.'
    end
    respond_to do |format|
      format.html { redirect_to students_path }
      format.js   # This will render create.js.erb
    end
  end

  def edit
    respond_to do |format|
      format.json { render json: @student.slice(:name, :subject, :marks) }
    end
  end

  def update
    if @student.update(student_params)
      flash[:notice] = 'Student was successfully updated.'
    else
      flash.now[:alert] = 'Error updating student. Please try again.'
    end
    respond_to do |format|
      format.html { redirect_to students_path }
      format.js   # This will render update.js.erb
    end
  end

  def destroy
    @student.destroy
    flash[:notice] = 'Student was successfully deleted.'
    respond_to do |format|
      format.html { redirect_to students_path }
      format.js # This will render destroy.js.erb
    end
  end

  private

  def set_student
    @student = current_teacher.students.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :subject, :marks)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/students_helper.rb
# frozen_string_literal: true

module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeacherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Include jQuery and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> <!-- Full version of jQuery -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  </head>

  <body>
    <div class="container mt-4">
      <div id="flash-messages">
        <% flash.each do |key, message| %>
          <%= render 'shared/flash_messages', flash_type: (key == 'alert' ? 'danger' : 'success'), message: message %>
        <% end %>
      </div>
    </div>
    
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<div class="alert alert-<%= flash_type %> alert-dismissible fade show" role="alert">
  <%= message %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<script>
  setTimeout(function() {
    $('.alert').alert('close');
  }, 3000);
</script>

app/views/students/_edit_modal.html.erb
<!-- Edit Modal -->
<div class="modal fade" id="editStudentModal<%= student.id %>" tabindex="-1" role="dialog" aria-labelledby="editStudentModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editStudentModalLabel">Edit Student</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'student_form', student: student %>
      </div>
    </div>
  </div>
</div>

app/views/students/_student_form.html.erb
<%= form_with(model: student, local: false, remote: true, html: { id: "#{student.persisted? ? "edit_student_#{student.id}" : "new_student"}" }) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', id: 'student_name' %>
  </div>

  <div>
    <%= f.label :subject %>
    <%= f.text_field :subject, class: 'form-control', id: 'student_subject' %>
  </div>

  <div>
    <%= f.label :marks %>
    <%= f.number_field :marks, class: 'form-control', id: 'student_marks' %>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <%= f.submit student.persisted? ? "Save" : "Add", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/students/_student_row.html.erb
<!-- app/views/students/_student_row.html.erb -->
<tr id="student_<%= student.id %>">
  <td><%= student.name %></td>
  <td><%= student.subject %></td>
  <td><%= student.marks %></td>
  <td class="text-center">
    <%= link_to 'Edit', '#', class: 'btn btn-outline-dark', data: { toggle: 'modal', target: "#editStudentModal#{student.id}" } %>
    <%= link_to 'Delete', student_path(student), method: :delete, 
          data: { confirm: 'Are you sure you want to delete this student?' }, 
          remote: true, class: 'btn btn-outline-danger ms-2' %>
  </td>
</tr>

<!-- Edit Modal -->
<div class="modal fade" id="editStudentModal<%= student.id %>" tabindex="-1" role="dialog" aria-labelledby="editStudentModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editStudentModalLabel">Edit Student</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'student_form', student: student %>
      </div>
    </div>
  </div>
</div>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/create.js.erb
<% if @student.persisted? %>
  $('#students-table-body').append('<%= j render partial: "student_row", locals: { student: @student } %>');
   $('body').append('<%= j render partial: "edit_modal", locals: { student: @student } %>');
  
  $('#new_student')[0].reset();

  $('#flash-messages').html('<%= j render partial: "shared/flash_messages", locals: { flash_type: "success", message: "Student was successfully created." } %>');
  $('.close[data-dismiss="modal"]').trigger('click');
<% else %>
  $('#flash-messages').html('<%= j render partial: "shared/flash_messages", locals: { flash_type: "danger", message: "Error creating student. Please try again." } %>');
<% end %>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/destroy.js.erb
$('#student_<%= @student.id %>').remove();

$('#flash-messages').html('<%= j render partial: "shared/flash_messages", locals: { flash_type: "success", message: "Student was successfully deleted." } %>');

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h3>tailwebs.</h3>
    <div>
      <%= link_to 'Home', students_path, class: 'btn btn-outline-dark' %>
      <%= link_to 'Logout', destroy_teacher_session_path, method: :delete, class: 'btn btn-outline-danger' %>
    </div>
  </div>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Subject</th>
        <th>Mark</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody id="students-table-body">
      <% @students.each do |student| %>
        <%= render partial: 'student_row', locals: { student: student } %>
      <% end %>
    </tbody>
  </table>

  <div class="d-grid mt-4">
    <button class="btn btn-dark" data-toggle="modal" data-target="#addStudentModal">Add</button>
  </div>

  <!-- Add Modal -->
  <div class="modal fade" id="addStudentModal" tabindex="-1" role="dialog" aria-labelledby="addStudentModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addStudentModalLabel">Add Student</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render 'student_form', student: Student.new %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>

app/views/students/update.js.erb
<% if @student.errors.blank? %>
  $('#student_<%= @student.id %>').replaceWith('<%= j render partial: "student_row", locals: { student: @student } %>');

  $('#flash-messages').html('<%= j render partial: "shared/flash_messages", locals: { flash_type: "success", message: "Student was successfully updated." } %>');
  $('.close[data-dismiss="modal"]').trigger('click');
<% else %>
  $('#flash-messages').html('<%= j render partial: "shared/flash_messages", locals: { flash_type: "danger", message: "Error updating student. Please try again." } %>');
<% end %>